apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: k8s-resources-reader
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps", "pods", "services", "endpoints", "secrets" ]
    verbs: [ "get", "watch", "list" ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-resources-reader-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-resources-reader
  apiGroup: rbac.authorization.k8s.io