apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: kfje-namespace
spec:
  type: NodePort
  selector:
    app: post-service-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 32022